### ISSUE TITLE
Issue at install

### ISSUE THREAD

**Issue by FWA-FabriceDAVID** [d3vilh/vpntv#1]
Hi

I got issue when I ran the " ansible-playbook main.yml "

![image](https://github.com/d3vilh/vpntv/assets/8434473/97670c96-60de-4952-a26e-c1eb37025791)

I restarted but got same issue, I fill my client.ovpn with info from my VPN Provider too .

![Snag_2ac1c91](https://github.com/d3vilh/vpntv/assets/8434473/f76a2a66-183c-4dfb-bb3b-b99d01616941)

**Comment by d3vilh** [comment]
HI @txfab 
We need to know exact error openvpn-client unable to start.
Could you show:
```shell
journalctl -xe
systemctl status openvpn-client@client.service
```
Thank you

**Comment by FWA-FabriceDAVID** [comment]
Hi @d3vilh 

It seem it can't access my auth.txt
![image](https://github.com/d3vilh/vpntv/assets/8434473/5ed3fed0-6470-4532-9d28-62c7fb85071c)

![image](https://github.com/d3vilh/vpntv/assets/8434473/6735a88e-bc16-4a1e-bc57-03adcd6c95c1)

Is there another way to add login and password of my NordVPN for this connection?

Thanks

**Comment by d3vilh** [comment]
Yes, the client can't find credentials file.
It should look for it in `/etc/openvpn/client/` or `/etc/openvpn/` directory by default. Try to put it there.
If it still does to work, I'd try to set the full path: `auth-user-pass /home/fabpi/vpntv/client-ovpn/auth.txt` in the client config.

**Comment by d3vilh** [comment]
During the installation vpntv, copy user configuration data from `~/vpntv/client-ovpn/*` to `/etc/openvpn/client/`, then it runs  vpn-client, which pickup everything from `/etc/openvpn/client/`.

This means, my previous advice with full path was wrong. It still should work, but better to manually copy the auth.txt file into VPN client directory `/etc/openvpn/client/` and try to change this option: `auth-user-pass /etc/openvpn/client/auth.txt` into the same `/etc/openvpn/client/YOUR-CLIENT-CONF.ovpn` config file.

Then just restart daemon and it should be connected.

**Comment by FWA-FabriceDAVID** [comment]
Hi @d3vilh 
OKay greats it's work thank you !

**Comment by d3vilh** [comment]
Great. I'll pin it, to update documentation.
